const WINDOW_MOBILE_SIZE = 320;
const WINDOW_TABLET_SIZE = 425;
const WINDOW_DESKTOP_SIZE = 1024;

const constants = {
  WINDOW_MOBILE_SIZE,
  WINDOW_TABLET_SIZE,
  WINDOW_DESKTOP_SIZE
};

export default constants;
